name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: list files
      working-directory: /home/runner/work/minesweeper/minesweeper
      run: |
        pwd
    - name: make
      working-directory: /home/runner/work/minesweeper/minesweeper
      run: |
        make --version  # Display make version
        make  # Run make
