name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: make
      working-directory: ./
      run: |
        ls -la  # List files in the current directory
        make --version  # Display make version
        make  # Run make
